AWSTemplateFormatVersion : '2010-09-09'
Transform: AWS::Serverless-2016-10-31
Description: AWS SAM example with Flask

Globals:
  Api:
    BinaryMediaTypes:
      - '*~1*'

Resources:
  JakubSamHelloWorld: # TODO
    Type: AWS::Serverless::Function
    Properties:
      Handler: app.app
      Runtime: python3.6
      Timeout: 60
      Policies:
        - Version: '2012-10-17'
          Statement:
            - Effect: Allow
              Action:
                - s3:*
              Resource:
                - 'arn:aws:s3:::jakub-sam-hello-world-bucket/*' # TODO
      CodeUri: s3://jakub-aws-sam-lambdas/jakub-sam-hello-world.zip # TODO
      Events:
        HttpRoot:
          Type: Api
          Properties:
            Path: '/'
            Method: ANY
        HttpAll:
          Type: Api
          Properties:
            Path: '/{proxy+}'
            Method: ANY
  JakubSamHelloWorldBucket: # TODO
    Type: AWS::S3::Bucket
    Properties:
      BucketName: jakub-sam-hello-world-bucket # TODO
