AWSTemplateFormatVersion : '2010-09-09'
Transform: AWS::Serverless-2016-10-31
Description: AWS SAM example with Flask

Globals:
  Api:
    BinaryMediaTypes:
      - '*~1*'

Resources:
  SetYourAppName: # TODO
    Type: AWS::Serverless::Function
    Properties:
      Handler: app.app
      Runtime: python3.6
      Timeout: 60
      Policies:
        - Version: '2012-10-17'
          Statement:
            - Effect: Allow
              Action:
                - s3:*
              Resource:
                - 'arn:aws:s3:::Set-Your-Bucket-Name/*' # TODO
      CodeUri: s3://jakub-aws-sam-lambdas/lambda.zip # TODO
      Events:
        HttpRoot:
          Type: Api
          Properties:
            Path: '/'
            Method: ANY
        HttpAll:
          Type: Api
          Properties:
            Path: '/{proxy+}'
            Method: ANY
  SetYourS3Bucket: # TODO
    Type: AWS::S3::Bucket
    Properties:
      BucketName: Set-Your-Bucket-Name # TODO
