AWSTemplateFormatVersion : '2010-09-09'
Transform: AWS::Serverless-2016-10-31
Description: AWS SAM example with Flask

Globals:
  Api:
    BinaryMediaTypes:
      - '*~1*'

Resources:
  SetYourAppName: # TODO
    Type: AWS::Serverless::Function
    Properties:
      Handler: app.app
      Runtime: python3.6
      Timeout: 60
      Environment:
        Variables:
          S3_BUCKET_NAME: !Sub "${DemoBucket}"
      Policies:
        - Version: '2012-10-17'
          Statement:
            - Effect: Allow
              Action:
                - s3:*
              Resource:
                - !Sub "${DemoBucket.Arn}/*"
      CodeUri: s3://jakub-aws-sam-lambdas/lambda.zip # TODO - You have to create a bucket for storing lambda source code
      Events:
        HttpRoot:
          Type: Api
          Properties:
            Path: '/'
            Method: ANY
        HttpAll:
          Type: Api
          Properties:
            Path: '/{proxy+}'
            Method: ANY
  DemoBucket:
    Type: AWS::S3::Bucket
